### ISSUE TITLE
Post timeouts

### ISSUE THREAD

**Issue by ps2** [WildflowerSchools/sensei_uploader#14]
```
02-03 16:59:37.164 1905-13849/com.wildflower.sensei E/DataPublisherService$DataPublisherTask: Error trying to submit proximity events from File /storage/emulated/0/Android/data/com.wildflower.sensei/files/device_data/12_1486157773454.txt
                                                                                              java.net.SocketTimeoutException
                                                                                                  at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
                                                                                                  at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
                                                                                                  at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                                                  at okio.Okio$2.read(Okio.java:140)
                                                                                                  at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
                                                                                                  at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
                                                                                                  at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
                                                                                                  at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
                                                                                                  at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
                                                                                                  at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
                                                                                                  at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
                                                                                                  at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
                                                                                                  at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
                                                                                                  at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
                                                                                                  at okhttp3.RealCall.getResponse(RealCall.java:244)
                                                                                                  at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
                                                                                                  at com.wildflower.sensei.SenseiApplication$1.intercept(SenseiApplication.java:71)
                                                                                                  at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
                                                                                                  at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
                                                                                                  at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
                                                                                                  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
                                                                                                  at okhttp3.RealCall.execute(RealCall.java:57)
                                                                                                  at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                                                  at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89)
                                                                                                  at com.wildflower.sensei.service.DataPublisherService$DataPublisherTask.submitData(DataPublisherService.java:140)
                                                                                                  at com.wildflower.sensei.service.DataPublisherService$DataPublisherTask.doInBackground(DataPublisherService.java:115)
                                                                                                  at com.wildflower.sensei.service.DataPublisherService$DataPublisherTask.doInBackground(DataPublisherService.java:73)
                                                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                  at java.lang.Thread.run(Thread.java:818)
```

**Comment by hashbrown** [comment]
@ps2 I've seen this a few times when I was testing.  Once was when the service was actually down.  Also it can happen if testing against heroku dev instances that are cold.  The first request starts up the app server, but sometimes that's slow and the request times out.

The important bit here is that I use an Android service to manage this job, it should retry with a back-off until successful.
