### ISSUE TITLE
threading issues with UsbStreamParser

### ISSUE THREAD

**Issue by ps2** [WildflowerSchools/sensei_uploader#8]
I think multiple UsbStreamReader threads are being active at the same time, and that serial data is randomly being fed to different consumers:

https://gist.github.com/ps2/f829072efcd343f6e6eae3242efdd9a2#file-threading-log-L669-L688

**Comment by hashbrown** [comment]
That's certainly possible although I can't tell from that log without the thread ids.  The mother node service should be calling cancel() on the stream parser whenever it gets an exception or it times out. That should kill the loop in that thread and effectively end it.  I'll have to see if that cancel() operation is working as intended.

**Comment by ps2** [comment]
Yes, I agree that it seems like cancel() should have been called.  The "Timeout waiting for response from Mother device" exception is only thrown right after the cancel call.  But we should also see a "StreamParsing Cancelled" for that, and we don't see those until later in the logs (and those might be for other streams)

This would seem like a race condition, but for the fact that there is quite a bit of time that passes before the issue, during which I would expect to see the cancelled message.   Is it possible for that read() to block? Seems like normally it doesn't.  Or some other blocking call in there?

**Comment by ps2** [comment]
The earlier thread is still running after the cancel:

```
D/UsbStreamParser$USbStreamReader: Read 0 bytes for com.wildflower.sensei.utils.UsbStreamParser$USbStreamReader@9d8a43d
D/UsbStreamParser$USbStreamReader: Read 0 bytes for com.wildflower.sensei.utils.UsbStreamParser$USbStreamReader@9d8a43d
D/UsbStreamParser$USbStreamReader: Read 0 bytes for com.wildflower.sensei.utils.UsbStreamParser$USbStreamReader@9d8a43d
D/UsbStreamParser$USbStreamReader: Read 0 bytes for com.wildflower.sensei.utils.UsbStreamParser$USbStreamReader@9d8a43d
D/UsbStreamParser$USbStreamReader: Read 0 bytes for com.wildflower.sensei.utils.UsbStreamParser$USbStreamReader@9d8a43d
D/UsbStreamParser: Cancelling Parsing Stream: com.wildflower.sensei.utils.UsbStreamParser@35a59c9
E/MotherNodeService: Error occurred while retrieving data from device 1
                     java.lang.Exception: Timeout waiting for response from Mother device
                         at com.wildflower.sensei.service.MotherNodeService.readPages(MotherNodeService.java:347)
                         at com.wildflower.sensei.service.MotherNodeService.retrieveDeviceData(MotherNodeService.java:232)
                         at com.wildflower.sensei.service.MotherNodeService.access$400(MotherNodeService.java:48)
                         at com.wildflower.sensei.service.MotherNodeService$ServiceBinder.retrieveDeviceData(MotherNodeService.java:85)
                         at com.wildflower.sensei.ui.CollectDataActivity$DataCollectionTask.doInBackground(CollectDataActivity.java:414)
                         at com.wildflower.sensei.ui.CollectDataActivity$DataCollectionTask.doInBackground(CollectDataActivity.java:376)
                         at android.os.AsyncTask$2.call(AsyncTask.java:295)
                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                         at java.lang.Thread.run(Thread.java:818)
W/System.err: java.lang.Exception: Timeout waiting for response from Mother device
W/System.err:     at com.wildflower.sensei.service.MotherNodeService.readPages(MotherNodeService.java:347)
W/System.err:     at com.wildflower.sensei.service.MotherNodeService.retrieveDeviceData(MotherNodeService.java:232)
W/System.err:     at com.wildflower.sensei.service.MotherNodeService.access$400(MotherNodeService.java:48)
W/System.err:     at com.wildflower.sensei.service.MotherNodeService$ServiceBinder.retrieveDeviceData(MotherNodeService.java:85)
W/System.err:     at com.wildflower.sensei.ui.CollectDataActivity$DataCollectionTask.doInBackground(CollectDataActivity.java:414)
W/System.err:     at com.wildflower.sensei.ui.CollectDataActivity$DataCollectionTask.doInBackground(CollectDataActivity.java:376)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
D/MotherNodeService: Retrieving flash data for device 3
D/UsbStreamParser$USbStreamReader: Start Parsing Stream: com.wildflower.sensei.utils.UsbStreamParser$USbStreamReader@91e2583
D/UsbStreamParser$USbStreamReader: Read 0 bytes for com.wildflower.sensei.utils.UsbStreamParser$USbStreamReader@9d8a43d
D/UsbStreamParser$USbStreamReader: Read 0 bytes for com.wildflower.sensei.utils.UsbStreamParser$USbStreamReader@91e2583
D/UsbStreamParser$USbStreamReader: Read 0 bytes for com.wildflower.sensei.utils.UsbStreamParser$USbStreamReader@91e2583
D/UsbStreamParser$USbStreamReader: Read 0 bytes for com.wildflower.sensei.utils.UsbStreamParser$USbStreamReader@9d8a43d
D/UsbStreamParser$USbStreamReader: Read 0 bytes for com.wildflower.sensei.utils.UsbStreamParser$USbStreamReader@91e2583
D/UsbStreamParser$USbStreamReader: Read 0 bytes for com.wildflower.sensei.utils.UsbStreamParser$USbStreamReader@9d8a43d
D/UsbStreamParser$USbStreamReader: Read 0 bytes for com.wildflower.sensei.utils.UsbStreamParser$USbStreamReader@91e2583
```

**Comment by ps2** [comment]
Ah, I think it *is* a race condition; the next parse() is called before that loop can check cancelled state.

**Comment by hashbrown** [comment]
Yep there it is, nice catch.

**Comment by hashbrown** [comment]
I can make the call to cancel() block until it confirms the thread is complete.

**Comment by ps2** [comment]
I have fixes for that I'm cleaning up to commit.

**Comment by ps2** [comment]
I'll submit as a PR for you to review.

**Comment by hashbrown** [comment]
I figured ;)
